# Generated by Django 2.1.4 on 2018-12-15 01:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_caracteristica', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=20)),
                ('nome_logradouro', models.CharField(max_length=255)),
                ('numero', models.IntegerField(default=0)),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField(default=0)),
                ('numero_de_quarto', models.IntegerField(default=2)),
                ('numero_de_banheiros', models.IntegerField(default=2)),
                ('numero_de_vagas', models.IntegerField(default=2)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.FloatField(default=0)),
                ('preco_condominio', models.FloatField(default=0)),
                ('data_do_anuncio', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('data_venda', models.DateField(auto_now_add=True)),
                ('prazo_pagamento', models.DateField(blank=True, null=True)),
                ('pagamento_ok', models.BooleanField(default=False)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to=settings.AUTH_USER_MODEL)),
                ('imovel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venda', to='store.Imovel')),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='store.Status'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='store.Tipo'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_imoveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foto',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='store.Imovel'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='imovel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='store.Imovel'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='store.Imovel'),
        ),
    ]
