# Generated by Django 2.1.4 on 2018-12-16 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20181215_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='store.Imovel')),
                ('interessado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
