# Generated by Django 2.1.4 on 2018-12-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='data_mensagem',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
